export const mapping = {
  h1: "text-4xl font-bold mb-8",
  h2: "text-3xl font-semibold mb-6",
  h3: "text-xl font-semibold mb-4",
  h4: "text-lg font-semibold mb-3",
  h5: "text-md font-medium mb-2",
  h6: "text-sm font-medium mb-1",

  p: "leading-relaxed text-base mb-4",

  em: "italic",
  strong: "font-bold",
  mark: "bg-yellow-200 text-yellow-900 px-2 py-1 rounded-full",
  small: "text-sm",
  sub: "text-sm text-gray-600",
  sup: "text-sm text-gray-600",
  cite: "font-italic italic",
  q: "italic",
  time: "text-sm text-gray-500",
  code: "bg-gray-100 text-gray-800 p-2 rounded-md",
  var: "font-mono text-xs bg-gray-200 text-gray-800 px-2 py-1 rounded-md",
  samp: "font-mono text-xs bg-gray-200 text-gray-800 px-2 py-1 rounded-md",
  kbd: "px-2 py-1 font-mono text-xs bg-gray-700 text-white rounded-md",
  pre: "overflow-x-auto bg-gray-100 border border-gray-300 p-4 rounded-md",

  span: "",
  br: "",

  a: "hover:text-blue-600 hover:underline transition-colors duration-200 ease-in-out text-blue-500",
  area: "cursor-pointer",

  img: "rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200 ease-in-out",
  picture: "",

  iframe: "w-full h-[400px] aspect-square rounded-lg shadow-md overflow-hidden",
  embed: "",
  object: "",
  video: "w-full h-[400px] aspect-square rounded-lg shadow-md overflow-hidden",
  audio: "w-full h-[150px] aspect-square rounded-lg shadow-md overflow-hidden",
  track: "",

  table: "border-collapse collapse w-full",
  caption: "caption-side top text-sm text-gray-500",
  thead: "bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500",
  colgroup: "",
  col: "",
  tbody: "",
  tr: "",
  th: "py-2 px-4 text-left text-xs font-semibold text-gray-500 bg-gray-50",
  td: "py-2 px-4 text-left text-sm",

  form: "",
  fieldset: "",
  legend: "",
  label: "",
  input:
    "appearance-none block w-full bg-white border border-gray-400 hover:border-gray-500 rounded py-2 px-4 leading-tight focus:outline-none focus:ring-0 focus:border-blue-600 transition-colors duration-200 ease-in-out",
  select:
    "appearance-none block w-full bg-white border border-gray-400 hover:border-gray-500 rounded py-2 px-4 leading-tight focus:outline-none focus:ring-0 focus:border-blue-600 transition-colors duration-200 ease-in-out",
  textarea:
    "appearance-none block w-full bg-white border border-gray-400 hover:border-gray-500 rounded py-2 px-4 leading-tight focus:outline-none focus:ring-0 focus:border-blue-600 transition-colors duration-200 ease-in-out",
  button:
    "hover:bg-blue-600 text-blue-600 hover:text-white transition-colors duration-200 ease-in-out",
  output: "",
  progress: "bg-blue-100 h-2.5 rounded-full",
  meter: "bg-yellow-100 h-2.5 rounded-full",

  header: "",
  nav: "",
  main: "",
  footer: "",
  aside: "",
  article: "",
  section: "",
  figure: "",
  figcaption: "",
  dialog: "",
  details: "",
  summary: "",

  hr: "my-6 border-gray-200",

  base: "",
  meta: "",
  link: "",
  style: "",
  script: "",
  canvas: "w-full h-[300px]",
  svg: "w-full h-[300px]",
  math: "",
  ruby: "",
  rp: "",
  rt: "",
  rtf: "",
  noembed: "",
  noframes: "",
};
